day-125/project/models/__init__.py
from flask_sqlalchemy import SQLAlchemy
import click
from flask.cli import with_appcontext

db = SQLAlchemy()

def init_db():
    """Clear existing data and create new tables."""
    db.drop_all()
    db.create_all()

@click.command("init-db")
@with_appcontext
def init_db_command():
    """Clear existing data and create new tables."""
    init_db()
    click.echo("Initialized the database.")

def init_app(app):
    db.init_app(app)
    # db = SQLAlchemy(app)
    print("models.init_app ===> app.config SQLALCHEMY_DATABASE_URI:", app.config.get("SQLALCHEMY_DATABASE_URI", None))
    # db.init_app(app)
    app.cli.add_command(init_db_command)
    return db

day-125/project/models/profile.py
from . import db

class Profile(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20))
    birthday = db.Column(db.Date())
    createtime = db.Column(db.DateTime())
    about = db.Column(db.Text())

day-125/project/models/user.py
from . import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique= True, index= True)

day-125/project/forms/myform.py
from flask_wtf import FlaskForm
from wtforms import StringField, DateField, TextAreaField
from wtforms.validators import DataRequired, InputRequired

class MyForm(FlaskForm):
    name = StringField(label='Name', validators=[InputRequired()])
    birthday = DateField(label='Birthday', format="%Y-%m-%d", validators=[DataRequired('Invalided Date'),InputRequired()])
    about = TextAreaField(label='About')

day-125/project/__init__.py
from flask import Flask

from .config import config
from . import models, routes

def create_app(config_name='default'):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    models.init_app(app)
    routes.init_app(app)
    
    return app

day-125/project/routes/__init__.py
from .home import home_bp
from .profile import profile_bp

def init_app(app):
    app.register_blueprint(home_bp)
    app.register_blueprint(profile_bp)

day-125/project/routes/home.py
from flask import Blueprint
from flask import render_template

home_bp = Blueprint('home_bp', __name__)
print("routes/home.py __name__ is :", __name__)
@home_bp.route('/', methods=['GET', 'POST'])
def index():
    return render_template('index.html')

day-125/project/routes/profile.py
from flask import Blueprint, render_template, redirect, url_for
from ..models.profile import Profile
from ..forms.myform import MyForm
from ..models import db

profile_bp = Blueprint('profile_bp', __name__)

@profile_bp.route('/myprofile/<id>/')
def myprofile(id):
    profile = Profile.query.get(id)  # 利用参数 id 读取数据库记录
    return render_template('profile.html', profile=profile)  # 将结果送给模板做展示

@profile_bp.route('/createprofile/', methods=('GET', 'POST'))
def createprofile():
    form = MyForm()
    if form.validate_on_submit():  # 如果表单提交了 用表单数据创建 Profile 对象
        profile = Profile()
        profile.name = form.name.data
        profile.birthday = form.birthday.data
        profile.about = form.about.data or ""

        db.session.add(profile)
        db.session.commit()
        return redirect(url_for('.myprofile', id=profile.id))  # 跳转到展示页面
    else:
        return render_template('createprofile.html', form=form)  # 显示创建页面

day-125/project/templates/createprofile.html
{% macro render_field(field) %}
  <dt>{{ field.label }}:
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

<form method="POST">
    {{ form.csrf_token }}
    {{ render_field(form.name) }}
    {{ render_field(form.birthday) }}
    {{ render_field(form.about) }}
    <input type="submit" value="Submit">
</form>

day-125/project/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>Flask Project Structure</title>
    </head>
    <body>
        <h1>Welcome!</h1>
        <!--注意这里的 url_for 参数，由于是在 blueprint 中定义的 endppint，需要在前面指定 blueprint 名称-->
        <a href="{{url_for('profile_bp.createprofile')}}">创建配置</a>
    </body>
</html>

day-125/project/templates/profile.html
<h1>{{ profile.name }}'s Info </h1>
<dt>Name:</dt>
<dd>{{ profile.name }}</dd>
<dt>Birthday:</dt>
<dd>{{ profile.birthday }}</dd>
<dt>About:</dt>
<dd>{{ profile.about }} </dd>